# Generated by Django 3.0.5 on 2021-10-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='headers'),
        ),
    ]
